version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: zapsign
      POSTGRES_USER: zuser
      POSTGRES_PASSWORD: zpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zuser -d zapsign"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    env_file: 
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    command: bash -c "npm start -- --host 0.0.0.0"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  pgdata: 