version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: zapsign
      POSTGRES_USER: zuser
      POSTGRES_PASSWORD: zpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zuser -d zapsign"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python init_data.py && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,backend
      - DATABASE_URL=postgres://zuser:zpass@db:5432/zapsign
      - CORS_ALLOWED_ORIGINS=http://localhost:4200,http://127.0.0.1:4200
      - ZAPSIGN_BASE_URL=https://sandbox.api.zapsign.com.br/api/v1
      - ZAPSIGN_ORG_ID=3599
      - ZAPSIGN_API_TOKEN=fa895995-6797-49fe-8561-35102d37ba9bf44a60bf-0776-4dac-aeb6-cb97f4fc7632

  frontend:
    build:
      context: ./frontend
      target: development
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development

volumes:
  pgdata:
  frontend_node_modules:
