version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: zapsign
      POSTGRES_USER: zuser
      POSTGRES_PASSWORD: zpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zuser -d zapsign"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python init_data.py && python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-in-production}
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,backend
      - DATABASE_URL=postgres://zuser:zpass@db:5432/zapsign
      - CORS_ALLOWED_ORIGINS=http://localhost,http://127.0.0.1
      - ZAPSIGN_BASE_URL=https://sandbox.api.zapsign.com.br/api/v1
      - ZAPSIGN_ORG_ID=3599
      - ZAPSIGN_API_TOKEN=${ZAPSIGN_API_TOKEN:-fa895995-6797-49fe-8561-35102d37ba9bf44a60bf-0776-4dac-aeb6-cb97f4fc7632}

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

volumes:
  pgdata:
